### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by dari089** [TeamMidnightDust/MidnightControls#174] opened 2023-02-16 15:08 UTC
**Describe the bug**
When i open minecraft and connect my controller it says that may controller is connected, but i cant do anything. i use windows 11 and ds4. controller works fine in other games. yesterday it also worked in minecraft.

**To Reproduce**
1.open Minecraft with mod and connected controller
2. move 
4. dosent work

**Expected behavior**
should work

**Screenshots**
![image](https://user-images.githubusercontent.com/116582650/219402189-63670aa6-ba05-4251-8e22-32998710eddb.png)
**Desktop (please complete the following information):**
 - OS: windows 11
 - Minecraft 1.19
 - Fabric![image](https://user-images.githubusercontent.com/116582650/219402856-e1fc90ac-191c-4f0b-940c-367a426a40f3.png)
 - Mods ![image](https://user-images.githubusercontent.com/116582650/219403931-c16d7d8d-620e-443d-98ef-709e19420f6e.png)
 - Version [e.g. 1.0.0]
 - Branch [e.g. dev]

**Additional context**
I haven't changed anything in Minecraft.

**Comment by GardenBunny** [comment] 2023-02-17 01:09
Same issue as above. Turning my controller on after minecraft launches restores functionality.

**Comment by ghost** [comment] 2023-02-21 21:51
I'm having the same issue. Only mod installed is Midnight Controls and Fabric API. Minecraft 1.19.3, on macOS 13.1; controller recognized in the mod's modmenu but nothing works. Other applications and games work just fine with the controller.

Edit: I should have RTFM. I just now saw the download link to the mappings editor, did a quick walkthrough of the controller buttons and copied the mapping string into the mappings file in the modmenu. Reload – it works! But it's very sensitive. 😄 Don't know if this is the problem faced by the others here.

**Comment by mserajnik** [comment] 2023-03-03 22:38
@madisonaltamirano

May I ask what controller you are using? And was your controller displayed with an orange font, indicating an issue with the mappings as it states in the manual prior to using SLD2 Gamepad Tool and pasting the mappings string?

Because I'm also on macOS (13.2.1), MC 1.19.3 and latest Fabric API (no other mods) and while both controllers I've tried (PS5 DualSense and Switch Pro Controller, both connected via Bluetooth) are recognized by the plugin (it automatically enables controller mode and also displays the controller prompts in-game; controllers display with a white font in the settings) no inputs work. I've also tried using SDL2 Gamepad Tool to generate the mappings string for both of them, but that didn't make any difference.

Both controllers work fine on https://gamepad-tester.com too, so I feel like I'm missing something.

**Edit:** Actually, pressing the Home button on the Switch Pro Controller while in-game opens the Mac Launchpad, so maybe this indicates that the plugin isn't able to properly take control of the controller away from the OS.

**Edit 2:** After further testing with a PS4 DualShock, I figured out that connecting the controllers via Bluetooth seems to be the issue; they work fine when connected via cable, so I'll further investigate what the problem is when connecting via Bluetooth.

**Comment by Hydroquake** [comment] 2024-02-06 05:39
I'm having this same issue on MacOS 14.1 for when using a Pro Controller wired or wireless.

**Comment by Motschen** [comment] 2024-02-14 12:53
It seems like OG's problem is maybe just caused by the controller not being selected in the MidnightControls settings, or missing a mapping (refer to the README in that case).
The problem the commentators have seems to be related to #148, so I'm closing this one.
If it is in fact a whole different problem, feel free to comment again, and I'll reopen it.

**Closed as not planned by Motschen** 2024-02-14 12:53 UTC
Labels: bug
