### ISSUE TITLE
Option to change the hotkey for exiting an inventory

### ISSUE THREAD

**Issue by ArtfulAnya** [TeamMidnightDust/MidnightControls#94] opened 2022-08-24 00:46 UTC
I'm currently trying to set up this mod to be similar to another controller mod I was using, however not being the switch the hotkey for closing the inventory is making it impossible for me. I'm used to having the "Y" button on my controller open and close the inventory and the "B" button set to "quick move."

**Comment by Motschen** [comment] 2022-09-18 14:36
Duplicate of #93

**Closed as not planned by Motschen** 2022-09-18 14:36 UTC
Labels: enhancement
