### ISSUE TITLE
Switching from page to page

### ISSUE THREAD

**Issue by JBuckets33** [TeamMidnightDust/MidnightControls#246] opened 2023-11-30 16:57 UTC
While in the inventory, whenever I switch from page to page using the right trigger (RT) and left trigger (LT) on my Xbox One controller, instead of going to the next page, it jumps 2 pages ahead. I included a screen recording of what it looks like in game. In the screen recording I am playing using Conquest Reforged 1.19.2 on fabric and am using theses versions of the midnight controls mod:

1. midnightcontrols-1.7.4+1.19.jar
2. midnightcontrols-extra-1.0.0.jar
3. midnightlib-fabric-1.0.0.jar

https://github.com/TeamMidnightDust/MidnightControls/assets/133781920/eceb2527-3f43-4f88-817d-ab2d01a912d3

**Comment by Motschen** [comment] 2023-12-23 21:57
Duplicate of #222 
Already fixed in the latest version, but I just don't have the time to backport it to 1.19.2, sorry.

**Closed as not planned by Motschen** 2023-12-23 21:57 UTC
Labels: bug
