### ISSUE TITLE
Menus just don’t open on steam deck

### ISSUE THREAD

**Issue by GoldenGunner1001** [TeamMidnightDust/MidnightControls#260] opened 2024-02-09 22:32 UTC
**Describe the bug**
When ever you open a menu of some kind and you exit, the last button you pressed before exiting the menu will repeatedly repress untill you restart the game.

**To Reproduce**
1. Pause the game/ open chest/ crafting menu
2. Exit by pressing B
3. Open any menu of any kind and it will immediately exit the menu

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Minecraft [e.g. 1.14.4]
 - Fabric [e.g. fabric 0.7.2+build.174]
 - Mods [e.g. aurora_keystrokes v1.0.0, modmenu
 - Branch [e.g. dev]

**Additional context**

**Comment by Motschen** [comment] 2024-02-14 13:55
Duplicate of #249

**Closed as not planned by Motschen** 2024-02-14 13:55 UTC
Labels: bug, duplicate, steam deck
