### ISSUE TITLE
Toggle Sprint/Sneak for controller behaving inconsistantly

### ISSUE THREAD

**Issue by VanishingBlaze** [TeamMidnightDust/MidnightControls#205] opened 2023-05-23 03:23 UTC
When using the toggle sneak or run I still have to hold for it to work. Normal or something I'm doing wrong?

**Comment by bisquickpancakemix** [comment] 2023-05-23 14:20
this mod is broken, its had issues with  sprinting since 1.19.2 but it hasnt been updated since march and the author no longer tracks or responds to issues. id recommend using the fabric port of controllable instead

**Comment by Motschen** [comment] 2024-02-14 13:19
Duplicate of #132

**Closed as not planned by Motschen** 2024-02-14 13:19 UTC
Labels: bug, duplicate, input
