### ISSUE TITLE
Nintendo Switch Pro Controller isn't working

### ISSUE THREAD

**Issue by TheMrBlueShowYt** [TeamMidnightDust/MidnightControls#203] opened 2023-05-03 14:16 UTC
**Describe the bug**
When I set my controller type to Nintendo Switch Pro Controller it doesn't let me click/do anything with the controller. (Edit: I also have BetterJoy installed and opened.)

**To Reproduce**
1. Go to MidnightControls settings
2. Set mode to Controller
3. Click on Controller Options
4. Select Nintendo Switch Pro Controller
5. Exit MidnightControls settings
6. See error

**Expected behavior**

**Screenshots**
I couldn't get any screenshots, but here's a video I took: [https://www.mediafire.com/file/jv0eacodx99ka8m/Minecraft_+1.19.4+2023-05-03+10-08-44.mp4/file](url)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft: 1.19.4
 - Fabric: 0.14.19
 - Mods: [https://www.mediafire.com/file/0psp2ubvipd5wpf/mods.zip/file](url)
 - Version: 1.8.1+1.19.4
 - Branch: 1.19.4

**Comment by bisquickpancakemix** [comment] 2023-05-06 16:56
There's no point in even posting your issue, the mod author hasn't replied to anyone having issues in a really long time. It's a shame ..

**Comment by Motschen** [comment] 2024-02-14 13:15
Duplicate of #10

**Closed as not planned by Motschen** 2024-02-14 13:15 UTC
Labels: bug, duplicate
