### ISSUE TITLE
Nintendo Pro Controller is ignored

### ISSUE THREAD

**Issue by Blackberrycak3** [TeamMidnightDust/MidnightControls#237] opened 2023-10-29 08:07 UTC
Ok so the midnight controls mod is not working with nintendo pro controller as shown here: #236

**Comment by diedthreetimes** [comment] 2023-11-24 03:47
Seems all controllers are affected.

**Comment by Motschen** [comment] 2024-02-14 13:16
Duplicate of #10

**Closed as not planned by Motschen** 2024-02-14 13:16 UTC
Labels: bug, duplicate, controller
