### ISSUE TITLE
XBox Elite Wireless Series 2 Controller SDL2 mappings not recognized by MidnightControls

### ISSUE THREAD

**Issue by heliovue** [TeamMidnightDust/MidnightControls#171] opened 2023-02-07 17:07 UTC
**Describe the bug**
MidnightControls is not recognizing Xbox Elite Wireless Series 2 controller mappings on MacOS.

**To Reproduce**
Launch Minecraft instance with Prism
Enter settings/controls menu
Click controller icon for midnightcontrols
Change control mode to Controller
Enter SDL2 mapping info from GamePad Tool since controller name is orange, indicating the mappings are not found
Confirmation that mapping has been updated appears
Controller inputs not recognized

**Expected behavior**
Input would be recognized by midnightcontrols

**Screenshots**
<img width="966" alt="Screenshot 2023-02-07 at 11 05 20 AM" src="https://user-images.githubusercontent.com/124538177/217298333-84af9f57-6378-4623-88a3-df049e435170.png">
<img width="966" alt="Screenshot 2023-02-07 at 11 05 35 AM" src="https://user-images.githubusercontent.com/124538177/217298322-aca11cfd-a567-406a-84f3-8331065badc3.png">
<img width="966" alt="Screenshot 2023-02-07 at 11 05 40 AM" src="https://user-images.githubusercontent.com/124538177/217298314-b7096047-35e2-49dc-9bd2-bb389d1a270f.png">
<img width="682" alt="Screenshot 2023-02-07 at 11 04 05 AM" src="https://user-images.githubusercontent.com/124538177/217298339-c527216b-64b2-471a-b17c-807919df270b.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.2
 - Minecraft 1.19.2
 - Fabric Loader 0.14.14 
 - Mods [Fabric API 0.73.2+1.19.2,MidnightControls 1.7.4+1.19.2]
 - Version [1.7.4]
 - Branch [1.19.2]

**Additional context**
While testing bindings, LT/RT sets as input and is corrected with Trigger Fix - but no other inputs are recognized. Config file shows mappings that were input in the midnight controls Minecraft interface. Other mappings from controller DB attempted as well) 

Controller works with:
Controllers app for MacOS
Minecraft Windows
Minecraft Java w/ Forge/Controllable Mod
Is recognized with gamepad-tool inputs and has SDL mappings identified
Miscellaneous websites

Controller firmware has been updated via Xbox Accessories app on Windows

Other versions of Minecraft with Fabric & Quilt were tested.

**Comment by youngchief-btw** [comment] 2023-02-15 05:08
@heliovue This issue is related: https://github.com/TeamMidnightDust/MidnightControls/issues/89. Does the workaround I gave work? Seems the Xbox Elite Series 2 controller has been giving problems on the latest versions of MacOS, along with other controllers it appears.

**Comment by Motschen** [comment] 2024-02-14 12:48
Duplicate of #89, although you provide a way more detailed description :)

**Closed as not planned by Motschen** 2024-02-14 12:48 UTC
Labels: bug
