### ISSUE TITLE
Controller Issues: Xbox One wired no longer able to drive boats

### ISSUE THREAD

**Issue by darkpitsimp** [TeamMidnightDust/MidnightControls#324] opened 2024-12-09 01:16 UTC
After new update my Xbox one controller cannot drive boats. I can ride passenger but I can’t drive it myself. This was not an issue in the last version of Minecraft I played 1.21.1 but in 1.21.3/4 it doesn’t work

I don’t know if it’ll happen to others but I downloaded the most recent version of midnightcontrols and other required mods and got on Minecraft. Make a boat and try to drive, it doesn’t move

**Expected behavior**
The boat to move forward in water

**Desktop (please complete the following information):**
 - Have you checked #263 No
 - the co troller has Bluetooth capability but the batteries don’t work no matter what I do so it is being played wired

 - OS: Windows 11
 - Minecraft 1.21.4
 - Fabric Loader 0.16.9
 - Fabric Api 0.111.0 + 1.21.4
 - Complementary shaders bound r5.3, dynamic FPS 3.7.7, essential mod 1.3.5.5, Iris shaders 1.8.3+1.2, lithium mc1.21.4, midnightlib 1.6.6-fab, modmenu 13.0.0-beta.1, sodium mc1.21.4, text placeholder api 2.5.1+1.21.3
 - midnightcontrols 1.10.2-fabric

**Additional context**
It worked in 1.21.1. Unlike usual, I didn’t just duplicate my instance in modrinth and update/pick mods out to create this modpack, I just created a new instance and redownloaded all the mods I wanted in the pack. This means it didn’t remember my settings, but I can’t offhand find a setting that would fix the boat movement problem

EDIT: I recreated the modpack on 1.21 and confirmed that it works, and then updated it to 1.21.1 and it still works, then starting at 1.21.2 the boats no longer work

**Comment by henry2222guapi** [comment] 2024-12-11 09:13
Good morning! 
How did you solve It?

**Comment by Motschen** [comment] 2024-12-11 13:04
This is caused by the massive code changes in 1.21.3
I'll see what I can do to fix it.

**Comment by henry2222guapi** [comment] 2024-12-11 13:08
If you can solve it please let me know, I really like playing with my boyfriend. We are from Brazil and many people here love your work

**Comment by Motschen** [comment] 2024-12-11 17:11
Fixed in 1.10.3 :)

**Closed as completed by Motschen** 2024-12-11 17:11 UTC
Labels: controller

**Comment by darkpitsimp** [comment] 2024-12-15 17:27
> Good morning! How did you solve It?

They released a new update that fixes it
