### ISSUE TITLE
The sprint bind sometimes act like a toogle

### ISSUE THREAD

**Issue by MidyGamy** [TeamMidnightDust/MidnightControls#193] opened 2023-04-06 22:44 UTC
**Describe the bug**
When using a controller, with "Toggle Sprint on Controller" set to off, the sprint action will be sometimes toggled when pressing multiple time

**To Reproduce**
1. Set any bind to "Sprint"
2. Start moving forward
3. Press multiple time the Sprint bind on the controller and start and stop moving (go on an ocean for more obvious result)
4. when not moving, press the Sprint bind on the controller or the keyboard

**Expected behavior**
Not toggling the sprint

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.19.4
 - Fabric 0.14.18
 - Version 1.8.0

**Comment by bisquickpancakemix** [comment] 2023-04-09 01:18
Same here, I hope the issue is fixed soon cause I've been dealing with it since 1.19.2 and even on 1.19.4 it's still there...

**Comment by Motschen** [comment] 2024-02-14 12:21
Duplicate of #132

**Closed as not planned by Motschen** 2024-02-14 12:21 UTC
Labels: bug
