### ISSUE TITLE
Unable to enter the game(T＿T)

### ISSUE THREAD

**Issue by chuan00100** [TeamMidnightDust/MidnightControls#37] opened 2022-06-18 16:45 UTC
**Describe the bug**
Unable to enter the game.Configuration conflict: there is more than one oshi.architecture.properties file on the classpath

**To Reproduce**
1. Install midnightcontrols-1.1.0+1.19
2. Install midnightlib-0.5.2
3. I tried to install only architectury-5.7.27-fabric fabric-api-0.56.0+1.19 and can't enter the game The error message remains the same

**Expected behavior**
Let me know the problem or fix the bug so that I can log into the game normally

**Screenshots**
![Snipaste_2022-06-19_00-44-08](https://user-images.githubusercontent.com/107765740/174448436-2c73d31c-c1f3-4e66-ad8f-92e5c84ce9c2.png)

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Minecraft [1.19]
 - Fabric [fabric 0.14.8]
 - Mods [architectury-5.7.27, cloth-config-7.0.72, continuity-2.0.0, CustomSkinLoader-14.14, fabric-api-0.56.0, indium-1.0.5, InventoryProfilesNext-1.5.3, iris-1.2.5, lithium-0.8.0, modmenu-4.0.0, RoughlyEnoughItems-9.0.489, sodium-1.19-0.4.2+build.16, starlight-1.1.1, Xaeros_Minimap-22.9.3, XaerosWorldMap-1.23.3]
 - Version [midnightlib-0.5.2, midnightcontrols-1.1.0]
 - Branch [-]

**Additio
nal context**
[latest.log](https://github.com/TeamMidnightDust/MidnightControls/files/8933974/latest.log)

**Comment by Bluebulu998** [comment] 2022-06-21 07:56
i met the same issue

**Comment by chuan00100** [comment] 2022-06-21 09:12
> i met the same issue

I reinstalled the system and the game and still got the same issue

**Comment by Motschen** [comment] 2022-06-24 19:42
Does this issue also happen without MidnightControls?

**Comment by Motschen** [comment] 2022-07-05 20:10
I'll close this until it's verified to be caused by MidnightControls

**Closed as not planned by Motschen** 2022-07-05 20:10 UTC
Labels: bug, question
