### ISSUE TITLE
(Steam Deck) Menu Navigation Problems.

### ISSUE THREAD

**Issue by DavidRLTG** [TeamMidnightDust/MidnightControls#145] opened 2022-12-11 18:12 UTC
**Describe the bug**
Basically, imagine:
I move Left Joystick up? it goes *left* on the menu instead.
I press Arrow Up? It goes ***left*** on the menu instead!
I move Right Joystick down? It goes *right* on the menu instead
***I press Arrow Down, it goes RIGHT on the menu instead***
Help!

**To Reproduce**
Just navigate on the menus.

**Expected behavior**
LJ UP makes the selection go up
LJ DOWN makes the selection go down
ARROW UP makes the selection go up
ARROW DOWN makes the selection go down

**Screenshots**
I can't really screenshot that..

**Desktop (please complete the following information):**
 - OS: [SteamOS 3]
 - Minecraft [1.19.2]
 - Fabric [Quilt Loader 0.17.6]
 - Mods [Only MidnightControls.]
 - Version [Latest]
 - Branch [Stable]

**Additional context**
If it matters, I use Prismlauncher, and the java version included with it.

**Comment by Motschen** [comment] 2023-01-03 19:12
Duplicate of #74

**Closed as not planned by Motschen** 2023-01-03 19:12 UTC
Labels: bug
