### ISSUE TITLE
cannot use Xbox Elite Series 2 controller under Arch Linux even after using custom mappings

### ISSUE THREAD

**Issue by DivineEssentia** [TeamMidnightDust/MidnightControls#147] opened 2022-12-12 04:45 UTC
**Describe the bug**
Even after using cusom mappings, I cannot use my controller on Arch at all since it cannot find the mappings. I also use xpadneo and xone. 

**To Reproduce**
1. Install xpadneo driver and connect controller
2. create a custom mapping
3. Start the mod
4. see that the name of the controller is yellow and nothing works

**Expected behavior**
I expected the controller to be functional

**Desktop (please complete the following information):**
 - OS: Arch Linux (6.0.11-arch1-1-t2)
 - Minecraft [1.19.0]
 - Fabric [fabric-0.14.9]
 - Mods [MidnightControls, Fabric API]
 - Version [1.7.0-1.19]
 - Branch [main]

**Additional context**
I have both the **xone** and **xpadneo** drivers installed for my controller so i can use the wired mode too. I have not seen any issues or incompatabilites in journalctl around it.

**Comment by Motschen** [comment] 2023-01-03 19:07
Please enable debug mode in the Advanced Config, restart the game with the controller plugged in, close it, and send me the log.

**Comment by impliedgg** [comment] 2023-01-12 08:39
Same issue here with an Xbox One S pad over USB2.
**Reproduction steps (assuming environment):**
  1. Launch SDL2 Gamepad Mapper ([aur package](https://aur.archlinux.org/packages/sdl2-gamepad-mapper))
  2. Make a mapping.
  3. Load using MidnightControls.
  4. Reload mappings.
  5. Try to bind anything.
  
  **Expected behavior:**
Bindings work without any issues. Controls work in-game.

**Actual behavior:**  
Only LT and RT are placed on a bind. Control does nothing in-game.

**Environment:**
  - Arch Linux, kernel 6.1.4-arch1-1
  - xpad driver
  - Minecraft 1.19.2
  - MidnightControls 1.7.4-1.19.3
  - Fabric 0.14.12, Fabric API 0.72.0
  - Modrinth release.

Worth noting that in the mapper tool and another game, the controller works as intended, so it's likely something with the SDL bindings or MidnightControls itself.

> restart the game with the controller plugged in, close it, and send me the log.

Logs are available [here](https://mclo.gs/M9nqjvF).

**edit**: mapping string if you need it:
```
030082795e040000ea0200000f050000,Xbox One S Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,-leftx:-a0,+leftx:+a0,-lefty:-a1,+lefty:+a1,-rightx:-a3,+rightx:+a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,
```

**Comment by Motschen** [comment] 2023-01-15 09:06
Try this mapping string:
`030000005e040000ea0200000f050000,Xbox One S Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,-leftx:-a0,+leftx:+a0,-lefty:-a1,+lefty:+a1,-rightx:-a3,+rightx:+a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,`

**Comment by Motschen** [comment] 2024-02-14 11:15
See #89

**Closed as not planned by Motschen** 2024-02-14 11:15 UTC
Labels: bug
