### ISSUE TITLE
Gyro support for switch and dualshock/dualsense controllers

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [TeamMidnightDust/MidnightControls#71] opened 2022-07-12 18:28 UTC
**Is your feature request related to a problem? Please describe.**
I feel that analog only aiming is obviously inferior to gyro aiming. I play splatoon 2, which supports gyro, and it makes gameplay much  better.

**Describe the solution you'd like**
I would like gyro to be added as a fine movement option. Perhaps optionally also disable vertical movement, with sensitivity options.

**Describe alternatives you've considered**
Steam allows direct mapping to mouse, however this defeats the purpose of the mod. Minecraft has many "states" which the mod accounts for but steam can't.

**Comment by DamianS-eng** [comment] 2022-07-15 15:04
Mentioned already in #5 

For now, you can launch PolyMC from Steam and set up a config that maps the gyro to Mouse input, maybe add Flick Stick to the right stick. The game doesn't care much about simultaneous mouse and controller input, and the controller glyphs can be manually selected in the settings. Only downside is poor inventory and menu navigation, but maybe an Action Set swap can salvage this in the mean time.

**Comment by Motschen** [comment] 2022-07-22 09:40
Closing this as it's a duplicate of #5

**Closed as completed by Motschen** 2022-07-22 09:40 UTC
Labels: enhancement
