### ISSUE TITLE
Crashing upon boot

### ISSUE THREAD

**Issue by Canimede** [TeamMidnightDust/MidnightControls#143] opened 2022-12-09 08:19 UTC
Mojang Logo briefly appears before game crashes

(This is my first report I am sincerely sorry if I am formatting incorrectly.)

**To Reproduce**
1. Launch Game

**Expected behavior**
Game should not crash

Linux, Steam Deck, Latest Build
PrismLauncher
Fabric, Fabric API, Sodium

**Additional context**
Following is the crash log:

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2022-12-09 03:07:00
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_481 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at eu.midnightdust.midnightcontrols.client.MidnightInput.handleAxe(MidnightInput.java:542)
	at eu.midnightdust.midnightcontrols.client.MidnightInput.fetchAxeInput(MidnightInput.java:281)
	at eu.midnightdust.midnightcontrols.client.MidnightInput.tickController(MidnightInput.java:140)
	at eu.midnightdust.midnightcontrols.client.MidnightControlsClient.onTick(MidnightControlsClient.java:209)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zeb000$onStartTick(class_310.java:3994)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 27 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [midnightcontrols.mixins.json:CreativeInventoryScreenAccessor from mod midnightcontrols] from phase [DEFAULT] in config [midnightcontrols.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 30 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_2896:I in net/minecraft/class_481 for midnightcontrols.mixins.json:CreativeInventoryScreenAccessor from mod midnightcontrols->@Accessor[FIELD_GETTER]::getSelectedTab()I [INJECT Applicator Phase -> midnightcontrols.mixins.json:CreativeInventoryScreenAccessor from mod midnightcontrols -> Apply Accessors ->  -> Locate -> midnightcontrols.mixins.json:CreativeInventoryScreenAccessor from mod midnightcontrols->@Accessor[FIELD_GETTER]::getSelectedTab()I]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1412)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at eu.midnightdust.midnightcontrols.client.MidnightInput.handleAxe(MidnightInput.java:542)
	at eu.midnightdust.midnightcontrols.client.MidnightInput.fetchAxeInput(MidnightInput.java:281)
	at eu.midnightdust.midnightcontrols.client.MidnightInput.tickController(MidnightInput.java:140)
	at eu.midnightdust.midnightcontrols.client.MidnightControlsClient.onTick(MidnightControlsClient.java:209)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zeb000$onStartTick(class_310.java:3994)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 5.13.0-valve21.3-1-neptune
	Java Version: 17.0.4.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 1870132736 bytes (1783 MiB) / 2380267520 bytes (2270 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0405
	Identifier: AuthenticAMD Family 23 Model 144 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 8
	Graphics card #0 name: VanGogh [AMD Custom GPU 0405]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x163f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8442.31
	Virtual memory used (MB): 5122.68
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 209.16
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.68.1+1.19.3
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e72
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7172
			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea72
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c72
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e72
			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f72
			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e72
			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b372
			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b372
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.11+49abcf7e72
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.9+2894d6df72
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe72
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.0.1+65e415cb72
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f72
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a072
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb72
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.38+df3654b372
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df72
			fabric-item-api-v1: Fabric Item API (v1) 2.1.4+fa25da9972
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.6+b7096da872
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3372
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b372
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df72
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.17+75e9821172
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.21+9e7660c672
			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da972
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.28+49abcf7e72
			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b72
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3972
			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b372
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.1.6+49abcf7e72
			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d72
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564672
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff72
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b72
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b372
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b372
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e72
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab72
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.38+8c84281072
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.10+689f5e7172
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.6+75e9821172
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.11+28ac448f72
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.1.0+0efcd39b72
		fabricloader: Fabric Loader 0.14.11
		iris: Iris 1.4.6
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		midnightcontrols: MidnightControls 1.7.1+22w43a
			midnightlib: MidnightLib 0.6.1-22w43a
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
			spruceui: SpruceUI 4.0.0+1.19
		minecraft: Minecraft 1.19.3
		sodium: Sodium 0.4.6+build.20
			fabric-api-base: Fabric API Base 0.4.19+8d1895cf72
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f72
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46372
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.2+f6c919d672
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve21.3-1-neptune) GL version 4.6 (Core Profile) Mesa 22.2.4 (git-80df10f902), AMD
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: English (US)
	CPU: 8x AMD Custom APU 0405

**Comment by mustafakamran98** [comment] 2022-12-09 10:35
This seems to be a duplicate of (#141). Could you close this issue and post your error logs as a comment over in the issue I posted?

**Comment by Motschen** [comment] 2022-12-09 17:49
Duplicate of #141

**Closed as not planned by Motschen** 2022-12-09 17:49 UTC
Labels: bug
